// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ListSearchableFieldsRequest struct {
	// Name of the dataset.
	Dataset string `pathParam:"style=simple,explode=false,name=dataset"`
	// Version of the dataset.
	Version string `pathParam:"style=simple,explode=false,name=version"`
}

func (o *ListSearchableFieldsRequest) GetDataset() string {
	if o == nil {
		return ""
	}
	return o.Dataset
}

func (o *ListSearchableFieldsRequest) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}

type ListSearchableFieldsResponse struct {
	// The dataset API for the given version is found and it is accessible to consume.
	TwoHundredApplicationJSONString *string
	// The combination of dataset name and version is not found in the system or it is not published yet to be consumed by public.
	FourHundredAndFourApplicationJSONString *string
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListSearchableFieldsResponse) GetTwoHundredApplicationJSONString() *string {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONString
}

func (o *ListSearchableFieldsResponse) GetFourHundredAndFourApplicationJSONString() *string {
	if o == nil {
		return nil
	}
	return o.FourHundredAndFourApplicationJSONString
}

func (o *ListSearchableFieldsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListSearchableFieldsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListSearchableFieldsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
