// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ListSearchableFieldsRequest struct {
	// Name of the dataset.
	Dataset string `pathParam:"style=simple,explode=false,name=dataset"`
	// Version of the dataset.
	Version string `pathParam:"style=simple,explode=false,name=version"`
}

type ListSearchableFieldsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The dataset API for the given version is found and it is accessible to consume.
	ListSearchableFields200ApplicationJSONString *string
	// The combination of dataset name and version is not found in the system or it is not published yet to be consumed by public.
	ListSearchableFields404ApplicationJSONString *string
}
