// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/FHOF/terraform-provider-Test1234/internal/sdk/pkg/models/shared"
	"net/http"
)

type ListDataSetsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns a list of data sets
	DataSetList *shared.DataSetList
}

func (o *ListDataSetsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListDataSetsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListDataSetsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListDataSetsResponse) GetDataSetList() *shared.DataSetList {
	if o == nil {
		return nil
	}
	return o.DataSetList
}
