// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Test1234/internal/sdk/pkg/models/shared"
	"net/http"
)

type ListDataSetsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns a list of data sets
	DataSetList *shared.DataSetList
}
